project_name: geektime-dl
env:
  - GO111MODULE=on
builds:
- env:
    - CGO_ENABLED=0
  binary: geektime-dl
  goos:
    - windows
    - darwin
    - linux
    - freebsd
    - openbsd
    - netbsd
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  ignore:
    - goos: freebsd
      goarch: arm
      goarm: 6
    - goos: openbsd
      goarch: arm
      goarm: 6
    - goos: darwin 
      goarch: 386
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^tests'
      - Merge pull request
      - Merge branch
archives:
-
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}_v{{ .Arm }}{{ end }}'
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - none*
  wrap_in_directory: false
  replacements:
    amd64: 64-bit
    386: 32-bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
    openbsd: OpenBSD
    netbsd: NetBSD
    freebsd: FreeBSD
release:
  draft: true
